# sssd: Configure
---
- name: krb5 | copy the krb5.conf template file
  template:
    src: templates/krb5.conf.j2
    dest: /etc/krb5.conf
    mode: 0644
  tags: [ krb5, sssd ]

- name: Copy the secret to tmp
  template:
    src: templates/secrets.j2
    dest: /tmp/my.secret
  tags: [ secrets, sssd ]

- name: Initialize Kerberos and generate a keytab file
  command: kinit --password-file=/tmp/my.secret "{{ bind_user }}"
  no_log: true
  tags: [ sssd_conf, keytab ]

- name: Remove my.secret
  file:
    path: /tmp/my.secret
    state: absent

- name: bind server to AD 1 of 2
  command: msktutil -N -c -b 'CN=COMPUTERS' -s {{ hostname|upper }}/{{ hostname }}.prod.mco -k my-keytab.keytab --computer-name {{ hostname }} --upn {{ hostname }}$ --server dnn1-windom01.prod.mco --user-creds-only
  become: yes
  tags: [ sssd_conf, bind ]

- name: bind server to AD 2 of 2
  command: msktutil -N -c -b 'CN=COMPUTERS' -s {{ hostname|upper }}/{{ hostname }} -k my-keytab.keytab --computer-name {{ hostname }} --upn {{ hostname }}$ --server dnn1-windom01.prod.mco --user-creds-only
  become: yes
  tags: [ sssd_conf, bind ]

- name: Move keytab file to sssd_conf
  command: mv my-keytab.keytab /etc/sssd/my-keytab.keytab
  tags: [ sssd_conf, keytab ]

- name: sssd | copy the sssd conf file
  template:
    src: templates/sssd.conf.j2
    dest: /etc/sssd/sssd.conf
    mode: 0600
  tags: [ sssd_conf,sssd]

  # Debian

- name: sssd | copy the pam conf file
  template:
    src: files/common-session.yml
    dest: /etc/pam.d/common-session
  tags: [ pam_conf,sssd]

  # Debian
- name: sssd | restart sssd service
  systemd:
    name: sssd
    enabled: yes
    state: restarted
  tags: [ sssd_conf, sssd, sssd_finish]

- name: Add domain admins to sudoers
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%Domain\ Admins\s'
    line: '%Domain\ Admins ALL=(ALL:ALL) ALL'
